CREATE DATABASE ABC;
USE ABC;
CREATE TABLE train (
TRAINID INT PRIMARY KEY,
TRAINNUMBER VARCHAR(20),
TRAINNAME VARCHAR(50),
SOURCSTATION VARCHAR(50),
DESTINATIONSTATION VARCHAR(50)
);

CREATE TABLE DRIVER(
DRIVERID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT
);

CREATE TABLE PLATFORM(
PLATFORMID INT PRIMARY KEY,
NAME VARCHAR(50),
DISSTRICTNAME VARCHAR(50)
);

CREATE TABLE TRAINPLATFORMSTOP(
STOPID INT PRIMARY KEY,
TRAINID INT,
PLATFORMID INT,
ARRIVALTIME TIME,
DEPARTURETIME TIME,
FOREIGN KEY (TRAINID)REFERENCES
TRAIN(TRAINID),
FOREIGN KEY(PLATFORMID)
REFERENCES PLATFORM(PLATFORMID)
);

SELECT * FROM TRAIN ;


